// <auto-generated />
using System;
using CourseManager.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CourseManager.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260526140827_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("CourseManager.Server.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("CourseId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("CourseManager.Server.Models.CourseFile", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FileAssetId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CourseId", "FileAssetId");

                    b.HasIndex("FileAssetId");

                    b.ToTable("CourseFiles");
                });

            modelBuilder.Entity("CourseManager.Server.Models.CoursePerson", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CourseId", "PersonId");

                    b.HasIndex("PersonId");

                    b.ToTable("CoursePeople");
                });

            modelBuilder.Entity("CourseManager.Server.Models.CourseSection", b =>
                {
                    b.Property<int>("CourseSectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("CourseSectionId");

                    b.HasIndex("CourseId");

                    b.ToTable("CourseSections");
                });

            modelBuilder.Entity("CourseManager.Server.Models.CourseSectionFile", b =>
                {
                    b.Property<int>("CourseSectionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FileAssetId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CourseSectionId", "FileAssetId");

                    b.HasIndex("FileAssetId");

                    b.ToTable("CourseSectionFiles");
                });

            modelBuilder.Entity("CourseManager.Server.Models.CourseSectionPerson", b =>
                {
                    b.Property<int>("CourseSectionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CourseSectionId", "PersonId");

                    b.HasIndex("PersonId");

                    b.ToTable("CourseSectionPeople");
                });

            modelBuilder.Entity("CourseManager.Server.Models.FileAsset", b =>
                {
                    b.Property<int>("FileAssetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CloudPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageProvider")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("FileAssetId");

                    b.HasIndex("FileName");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("CourseManager.Server.Models.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CourseSectionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("GroupId");

                    b.HasIndex("CourseSectionId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("CourseManager.Server.Models.GroupFile", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FileAssetId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GroupId", "FileAssetId");

                    b.HasIndex("FileAssetId");

                    b.ToTable("GroupFiles");
                });

            modelBuilder.Entity("CourseManager.Server.Models.GroupPerson", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GroupId", "PersonId");

                    b.HasIndex("PersonId");

                    b.ToTable("GroupPeople");
                });

            modelBuilder.Entity("CourseManager.Server.Models.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("PersonId");

                    b.HasIndex("FullName");

                    b.ToTable("People");
                });

            modelBuilder.Entity("CourseManager.Server.Models.PersonFile", b =>
                {
                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FileAssetId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PersonId", "FileAssetId");

                    b.HasIndex("FileAssetId");

                    b.ToTable("PersonFiles");
                });

            modelBuilder.Entity("CourseManager.Server.Models.CourseFile", b =>
                {
                    b.HasOne("CourseManager.Server.Models.Course", "Course")
                        .WithMany("CourseFiles")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseManager.Server.Models.FileAsset", "FileAsset")
                        .WithMany("CourseFiles")
                        .HasForeignKey("FileAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("FileAsset");
                });

            modelBuilder.Entity("CourseManager.Server.Models.CoursePerson", b =>
                {
                    b.HasOne("CourseManager.Server.Models.Course", "Course")
                        .WithMany("CoursePeople")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseManager.Server.Models.Person", "Person")
                        .WithMany("CoursePeople")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("CourseManager.Server.Models.CourseSection", b =>
                {
                    b.HasOne("CourseManager.Server.Models.Course", "Course")
                        .WithMany("CourseSections")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("CourseManager.Server.Models.CourseSectionFile", b =>
                {
                    b.HasOne("CourseManager.Server.Models.CourseSection", "CourseSection")
                        .WithMany("CourseSectionFiles")
                        .HasForeignKey("CourseSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseManager.Server.Models.FileAsset", "FileAsset")
                        .WithMany("CourseSectionFiles")
                        .HasForeignKey("FileAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CourseSection");

                    b.Navigation("FileAsset");
                });

            modelBuilder.Entity("CourseManager.Server.Models.CourseSectionPerson", b =>
                {
                    b.HasOne("CourseManager.Server.Models.CourseSection", "CourseSection")
                        .WithMany("CourseSectionPeople")
                        .HasForeignKey("CourseSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseManager.Server.Models.Person", "Person")
                        .WithMany("CourseSectionPeople")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CourseSection");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("CourseManager.Server.Models.Group", b =>
                {
                    b.HasOne("CourseManager.Server.Models.CourseSection", "CourseSection")
                        .WithMany("Groups")
                        .HasForeignKey("CourseSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseSection");
                });

            modelBuilder.Entity("CourseManager.Server.Models.GroupFile", b =>
                {
                    b.HasOne("CourseManager.Server.Models.FileAsset", "FileAsset")
                        .WithMany("GroupFiles")
                        .HasForeignKey("FileAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CourseManager.Server.Models.Group", "Group")
                        .WithMany("GroupFiles")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileAsset");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("CourseManager.Server.Models.GroupPerson", b =>
                {
                    b.HasOne("CourseManager.Server.Models.Group", "Group")
                        .WithMany("GroupPeople")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseManager.Server.Models.Person", "Person")
                        .WithMany("GroupPeople")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("CourseManager.Server.Models.PersonFile", b =>
                {
                    b.HasOne("CourseManager.Server.Models.FileAsset", "FileAsset")
                        .WithMany("PersonFiles")
                        .HasForeignKey("FileAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CourseManager.Server.Models.Person", "Person")
                        .WithMany("PersonFiles")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileAsset");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("CourseManager.Server.Models.Course", b =>
                {
                    b.Navigation("CourseFiles");

                    b.Navigation("CoursePeople");

                    b.Navigation("CourseSections");
                });

            modelBuilder.Entity("CourseManager.Server.Models.CourseSection", b =>
                {
                    b.Navigation("CourseSectionFiles");

                    b.Navigation("CourseSectionPeople");

                    b.Navigation("Groups");
                });

            modelBuilder.Entity("CourseManager.Server.Models.FileAsset", b =>
                {
                    b.Navigation("CourseFiles");

                    b.Navigation("CourseSectionFiles");

                    b.Navigation("GroupFiles");

                    b.Navigation("PersonFiles");
                });

            modelBuilder.Entity("CourseManager.Server.Models.Group", b =>
                {
                    b.Navigation("GroupFiles");

                    b.Navigation("GroupPeople");
                });

            modelBuilder.Entity("CourseManager.Server.Models.Person", b =>
                {
                    b.Navigation("CoursePeople");

                    b.Navigation("CourseSectionPeople");

                    b.Navigation("GroupPeople");

                    b.Navigation("PersonFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
